# Generated by Django 3.2.9 on 2021-11-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PrintIt', '0002_auto_20211109_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cip_address',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='uip_address',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userc_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
