# Generated by Django 3.2.9 on 2021-11-09 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PrintIt', '0008_auto_20211109_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_extendeduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_node', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatusmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatusmap',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_orderstatusmap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_price', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='updated_by',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='useru_userlocation', to=settings.AUTH_USER_MODEL),
        ),
    ]
