# Generated by Django 3.2.9 on 2021-11-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintIt', '0009_auto_20211109_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='cip_address',
        ),
        migrations.RemoveField(
            model_name='status',
            name='uip_address',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_by',
        ),
    ]
