# Generated by Django 3.2.9 on 2021-11-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintIt', '0011_auto_20211109_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='node_id',
            new_name='node',
        ),
    ]
