# Generated by Django 3.2.9 on 2021-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintIt', '0014_auto_20211111_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
